# Generated by Django 4.0.5 on 2022-06-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Supplier Name')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=200, verbose_name='Description')),
                ('note', models.TextField(verbose_name='Note')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('availability', models.BooleanField(default=False, verbose_name='Availability')),
                ('supplier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
